### ISSUE TITLE
IOS charts not loading if its not in focus

### ISSUE THREAD

**Issue by mohanhari** [entronad/flutter_echarts#101]
I am trying to build multiple charts in a single page just like the example you gave. It's working fine in android but when run that on IOS the charts that are visible are only rendering. The other charts are not rendering. I thought it might be my problem but when I tried to run the example app in this repo its also not rendering in IOS but in android its working fine. Any idea why it's happening?
my Flutter version 1.22.4
echarts version ^1.5.0

**Comment by jakthegr8** [comment]
I too facing the same issue. With the given example, when we add multiple charts (let's say 3 charts) in a `Column` component, the visible charts(first 1 & 2 charts) are loading fine and the hidden ( last 3rd charts) is not loading. 

In order to make it working, we have to scroll to the 3rd chart to make it visible, So that 3rd  chart is loading fine. However, the first is not loading in that case.

It would be great if the core team take a look at this issue and give us at least suggestion instead of full solution.

**Comment by entronad** [comment]
Please see and discuss in this issue: #104 .

**Comment by entronad** [comment]
Please update to v2.1.0 and try setting `reloadAfterInit` to `true`.
Details discussed in https://github.com/entronad/flutter_echarts/issues/124 .
