### ISSUE TITLE
image url

### ISSUE THREAD

**Issue by lironiz** [entronad/flutter_echarts#17]
I have a flutter project using flutter_echarts.
I want to add icons to my yAxis, using rich text. the icons are in assets/images/imageName.png,
but when I use it like this in 'rich'

```
backgroundColor: {
                           image: './assets/images/imageName.png'
                           },
                      },
```

or like this
```
backgroundColor: {
                           image: 'assets/images/imageName.png'
                           },
                      },
```

the icon is not displayed.
is there another way?

**Comment by entronad** [comment]
@lironiz 

Because this lib abstract web assets to strings, you could not directly handle imge files.
The solution is to use [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) , Echarts image property allows all legal URL forms, so just transform your image asset to a Base64 Data URL string just like we often do in CSS.
If you are not familiar with CSS Base64 Data URL, please search for docs like: https://stackoverflow.com/questions/17090571/is-there-a-way-to-set-background-image-as-a-base64-encoded-image
